#!/usr/bin/env bash
#
#  dashbased The Dashbase Core server.
#
#
# chkconfig: 345 80 20
# description: dashbased
# processname: dashbased
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/dashbased, see below
if [ -f /etc/sysconfig/dashbased ]; then
        . /etc/sysconfig/dashbased
fi

RETVAL=0

prog=dashbased
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/dashbased
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/dashbased}

# dashbased defaults to /usr/bin/dashbased, override with BITCOIND_BIN
dashd=${BITCOIND_BIN-/usr/bin/dashbased}

# dashbased opts default to -disablewallet, override with BITCOIND_OPTS
dashd_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $dashd $dashd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
